# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: {{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run build-storybook --workspace storybook-app
    - run: npm i -g gh-pages
    - run: git config user.name github-action
    - run: git config user.email github-actions@github.com
    - run: npx gh-pages -d apps/storybook-app/storybook-static
